[theme]
primaryColor = '#027DA4' # Accent color for interactive elements
backgroundColor = '#0D0630' # Background color for the main content area
secondaryBackgroundColor = '#007633' # Background color for sidebar and most widgets
textColor = '#FFFFFF'
font = "serif"